FUNC LABEL 0
    PRINT REG 0
    PRINT REG 1
    MOV REG 0 VAL 25
    MOV REG 1 VAL 44
    ADD REG 0 REG 1
    PRINT REG 0
    PRINT REG 1
    MOV REG 0 VAL 150
    MOV REG 1 VAL 156
    PRINT REG 0
    PRINT REG 1
    ADD REG 1 REG 0
    PRINT REG 1
    PRINT REG 0
    RET