FUNC LABEL 0
    MOV STK A VAL 10
    MOV STK B VAL 255
    MOV REG 0 STK B
    NOT REG 0
    EQU REG 0
    REF REG 1 STK A
    CAL VAL 5
    RET
FUNC LABEL 5
    MOV STK A REG 1
    PRINT PTR A
    MOV PTR A VAL 20
    MOV REG 1 PTR A
    PRINT PTR A
    PRINT REG 0
    ADD REG 0 REG 1
    PRINT REG 0
    MOV
    RET