FUNC LABEL 0
    MOV STK A VAL 3
    PRINT STK A
    MOV REG 0 STK A
    PRINT REG 0
    MOV STK B VAL 10
    PRINT STK B
    MOV STK A STK B
    PRINT STK A
    PRINT STK B
    REF REG 1 STK A
    MOV STK A VAL 5
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV STK A REG 1
    PRINT PTR A
    RET