FUNC LABEL 0
    MOV REG 0 VAL 0
    MOV REG 1 VAL 255
    PRINT REG 0
    PRINT REG 1
    NOT REG 0
    NOT REG 1
    PRINT REG 0
    PRINT REG 1
    MOV REG 2 VAL 133
    NOT REG 2
    PRINT REG 2
    NOT REG 2
    PRINT REG 2
    RET