FUNC LABEL 0
    MOV STK A VAL 13
    REF REG 0 STK A
    REF STK B STK A
    PRINT PTR B
    MOV STK A VAL 20
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV STK A REG 0
    PRINT PTR A
    MOV PTR A VAL 5
    REF STK B PTR A
    PRINT PTR B
    RET